name: Deploy to VPS

on:
  push:
    branches:
      - main  # Ou master, selon votre branche par défaut

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /var/www/portfolio
            
            # Pull des dernières modifications
            git pull origin main
            
            # Installation des dépendances (seulement si package.json a changé)
            npm install --production=false
            
            # Build de l'application
            npm run build
            
            # Redémarrage avec PM2
            pm2 reload ecosystem.config.js --update-env
            
            # Afficher le statut
            pm2 status portfolio