name: React Portfolio

run-name: Deploy to ubuntu VPS by @${{ github.actor }}

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            cd ${{ secrets.VPS_PROJECT_PATH }}
            pm2 stop ${{ secrets.APP_ID }}
            sudo git pull origin
            npm install
            npm run build
            pm2 start ${{ secrets.APP_ID }}